# Generated by Django 3.2.13 on 2022-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dsnid',
            field=models.IntegerField(default=123),
        ),
    ]
