# Generated by Django 3.2.13 on 2022-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20220509_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dsnid',
            field=models.IntegerField(default=123),
        ),
    ]
