# Generated by Django 3.2.13 on 2022-05-12 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_customuser_dsnid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='track',
        ),
        migrations.AddField(
            model_name='mentor',
            name='tracks',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Lead'), (2, 'Mentor'), (3, 'Mentee')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=24)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('mentors', models.ManyToManyField(to='user_app.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('phone', models.IntegerField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
