# Generated by Django 3.2.13 on 2022-05-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_mentor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
