# Generated by Django 3.2.13 on 2022-05-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_mentor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='mentors',
        ),
    ]
