# Generated by Django 3.2.13 on 2022-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20220513_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='tracks',
        ),
        migrations.AddField(
            model_name='mentor',
            name='tracks',
            field=models.ManyToManyField(to='user_app.Track'),
        ),
    ]
