# Generated by Django 3.2.13 on 2022-05-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20220513_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='tracks',
            field=models.ManyToManyField(null=True, to='user_app.Track'),
        ),
    ]
