# Generated by Django 3.2.13 on 2022-05-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_auto_20220513_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, to='user_app.Track'),
        ),
    ]
