# Generated by Django 3.2.13 on 2022-05-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_mentor_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='tracks',
            field=models.ManyToManyField(to='user_app.Track'),
        ),
    ]
